version: '2'
services:
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - .:/www
    ports:
      - "8088:80"
      - "8443:443"
    env_file:
      - ./docker/.env